### ISSUE TITLE
SensorScanAngleVariable Bug

### ISSUE THREAD

**Issue by rmclaren** [rmclaren/bufr-query#26]
In SensorScanAngleVariable:

```cpp
if (sensor == "iasi")
{
   float tmp;
   tmp = -stepAdj;
   // Calculate sensor scan angle
   for (size_t idx = 0; idx < fovnObj->size(); idx++)
   {
      if (scanpos[idx] % 2 == 1)
      {
         tmp = stepAdj;
      }
      scanang[idx] = start + static_cast<float>((fovn[idx]-1)/4) * step + tmp;
   }
}
```

`tmp` starts being negative  of `stepAdj` but is mutated to be equal to `stepAdj` with the first odd numbered `scanpos`. It stays that way for the rest of the for loop execution.

**Comment by rmclaren** [comment]
@emilyhcliu Is the intention for the stepAdj to be negative for even numbered scan positions?

**Comment by rmclaren** [comment]
@JasonWelsh-NOAA Could you take aa look :)

**Comment by rmclaren** [comment]
@emilyhcliu Question. In the YAML mapping configuration:

```yaml
    sensorViewAngle:
      sensorScanAngle:
        fieldOfViewNumber: "*/FOVN"
        scanStart: -48.330
        scanStep: 3.334
        scanStepAdjust: 1.25
        sensor: iasi
```

Should the scanStart, scanStep, and scanStepAdjust angles really be configurable? It seems like these are just properties of IASI, (knowing the sensor is IASI should tell us this info)...
